export const IllustrationsSolid = {
  aligner: require("./icons/Aligner.png"),
  armour: require("./icons/Armour.png"),
  backpack: require("./icons/Backpack.png"),
  blueFlag: require("./icons/BlueFlag.png"),
  blueStar: require("./icons/BlueStar.png"),
  redBomb: require("./icons/Bomb_01.png"),
  grayBomb: require("./icons/Bomb_02.png"),
  redBook: require("./icons/Book_01.png"),
  blueBook: require("./icons/Book_02.png"),
  greenBook: require("./icons/Book_03.png"),
  bread: require("./icons/Bread.png"),
  cancel: require("./icons/Cancel.png"),
  carrot: require("./icons/Carrot.png"),
  chatbox: require("./icons/Chatbox.png"),
  chefHat: require("./icons/ChefHat.png"),
  coin: require("./icons/Coin.png"),
  crossSword: require("./icons/CrossSword.png"),
  goldCrown: require("./icons/Crown_01.png"),
  silverCrown: require("./icons/Crown_02.png"),
  bronzeCrown: require("./icons/Crown_03.png"),
  kingCrown: require("./icons/Crown.png"),
  mug: require("./icons/Cup.png"),
  cursor: require("./icons/Cursor.png"),
  egg: require("./icons/Egg.png"),
  enery: require("./icons/Energy.png"),
  eye: require("./icons/Eye.png"),
  friedEgg: require("./icons/FriedEgg.png"),
  gear: require("./icons/Gear.png"),
  gem: require("./icons/Gem.png"),
  yellowGift: require("./icons/GiftBox01.png"),
  blueGift: require("./icons/GiftBox02.png"),
  greenGift: require("./icons/GiftBox03.png"),
  purpleGift: require("./icons/GiftBox04.png"),
  redGift: require("./icons/GiftBox05.png"),
  heart: require("./icons/Heart.png"),
  key: require("./icons/Key.png"),
  keyBoss: require("./icons/KeyBoss.png"),
  keyGold: require("./icons/KeyGold.png"),
  leaf: require("./icons/Leaf.png"),
  magnet: require("./icons/Magnet.png"),
  meat: require("./icons/Meat.png"),
  money: require("./icons/Money.png"),
  pine: require("./icons/Pine.png"),
  redSmallPotion: require("./icons/Potion_01.png"),
  blueSmallPotion: require("./icons/Potion_02.png"),
  redBigPotion: require("./icons/Potion_Big_01.png"),
  redBluePotion: require("./icons/Potion_Big_02.png"),
  goldMedal: require("./icons/Rank_1.png"),
  silverMedal: require("./icons/Rank_2.png"),
  bronzeMedal: require("./icons/Rank_3.png"),
  redFlag: require("./icons/RedFlag.png"),
  snake: require("./icons/Snake.png"),
  spinWheel: require("./icons/SpinWheelIcon.png"),
  star: require("./icons/Star.png"),
  sword: require("./icons/Sword.png"),
  tick: require("./icons/Tick.png"),
  blueTreasureChest: require("./icons/TreasureChest_01.png"),
  redTreasureChest: require("./icons/TreasureChest_02.png"),
  greenTreasureChest: require("./icons/TreasureChest_03.png"),
  purpleTreasureChest: require("./icons/TreasureChest_04.png"),
  grayTreasureChest: require("./icons/TreasureChest_05.png"),
  goldTreasureChest: require("./icons/TreasureChest_06.png"),
  xp: require("./icons/XP.png"),
};

export const IllustrationsOutline = {
  aligner_outline: require("./icons/outline/Aligner.png"),
  armour_outline: require("./icons/outline/Armour.png"),
  backpack_outline: require("./icons/outline/Backpack.png"),
  blueFlag_outline: require("./icons/outline/BlueFlag.png"),
  blueStar_outline: require("./icons/outline/BlueStar.png"),
  redBomb_outline: require("./icons/outline/Bomb_01.png"),
  grayBomb_outline: require("./icons/outline/Bomb_02.png"),
  redBook_outline: require("./icons/outline/Book_01.png"),
  blueBook_outline: require("./icons/outline/Book_02.png"),
  greenBook_outline: require("./icons/outline/Book_03.png"),
  bread_outline: require("./icons/outline/Bread.png"),
  cancel_outline: require("./icons/outline/Cancel.png"),
  carrot_outline: require("./icons/outline/Carrot.png"),
  chatbox_outline: require("./icons/outline/Chatbox.png"),
  chefHat_outline: require("./icons/outline/ChefHat.png"),
  coin_outline: require("./icons/outline/Coin.png"),
  crossSword_outline: require("./icons/outline/CrossSword.png"),
  // goldCrown_outline: require("./icons/outline/Crown_01.png"),
  // silverCrown_outline: require("./icons/outline/Crown_02.png"),
  // bronzeCrown_outline: require("./icons/outline/Crown_03.png"),
  kingCrown_outline: require("./icons/outline/Crown.png"),
  mug_outline: require("./icons/outline/Cup.png"),
  cursor_outline: require("./icons/outline/Cursor.png"),
  egg_outline: require("./icons/outline/Egg.png"),
  enery_outline: require("./icons/outline/Energy.png"),
  eye_outline: require("./icons/outline/Eye.png"),
  friedEgg_outline: require("./icons/outline/FriedEgg.png"),
  gear_outline: require("./icons/outline/Gear.png"),
  gem_outline: require("./icons/outline/Gem.png"),
  yellowGift_outline: require("./icons/outline/GiftBox01.png"),
  blueGift_outline: require("./icons/outline/GiftBox02.png"),
  greenGift_outline: require("./icons/outline/GiftBox03.png"),
  purpleGift_outline: require("./icons/outline/GiftBox04.png"),
  redGift_outline: require("./icons/outline/GiftBox05.png"),
  heart_outline: require("./icons/outline/Heart.png"),
  key_outline: require("./icons/outline/Key.png"),
  keyBoss_outline: require("./icons/outline/KeyBoss.png"),
  keyGold_outline: require("./icons/outline/KeyGold.png"),
  leaf_outline: require("./icons/outline/Leaf.png"),
  magnet_outline: require("./icons/outline/Magnet.png"),
  meat_outline: require("./icons/outline/Meat.png"),
  money_outline: require("./icons/outline/Money.png"),
  pine_outline: require("./icons/outline/Pine.png"),
  redSmallPotion_outline: require("./icons/outline/Potion_01.png"),
  blueSmallPotion_outline: require("./icons/outline/Potion_02.png"),
  redBigPotion_outline: require("./icons/outline/Potion_Big_01.png"),
  redBluePotion_outline: require("./icons/outline/Potion_Big_02.png"),
  goldMedal_outline: require("./icons/outline/Rank_1.png"),
  silverMedal_outline: require("./icons/outline/Rank_2.png"),
  bronzeMedal_outline: require("./icons/outline/Rank_3.png"),
  redFlag_outline: require("./icons/outline/RedFlag.png"),
  snake_outline: require("./icons/outline/Snake.png"),
  spinWheel_outline: require("./icons/outline/SpinWheelIcon.png"),
  star_outline: require("./icons/outline/Star.png"),
  sword_outline: require("./icons/outline/Sword.png"),
  tick_outline: require("./icons/outline/Tick.png"),
  blueTreasureChest_outline: require("./icons/outline/TreasureChest_01.png"),
  redTreasureChest_outline: require("./icons/outline/TreasureChest_02.png"),
  greenTreasureChest_outline: require("./icons/outline/TreasureChest_03.png"),
  purpleTreasureChest_outline: require("./icons/outline/TreasureChest_04.png"),
  grayTreasureChest_outline: require("./icons/outline/TreasureChest_05.png"),
  goldTreasureChest_outline: require("./icons/outline/TreasureChest_06.png"),
  xp_outline: require("./icons/outline/XP.png"),
};

export const Illustrations = {
  ...IllustrationsSolid,
  ...IllustrationsOutline,
};
